### ISSUE TITLE
Menüü shooteril/ffa-l

### ISSUE THREAD

**Issue by crackdorium** [Netifriik/Ogar#3]
Kui sa valid ffa või shooteri siis all võiks õpetused valikut tehes muutuda.

Lasin mõnel joinida minuga shooterisse ja nad ei saanud aru, et viiruseid saab lasta ja nii. Lisaks võiks panna mingi descriptioni sinna: Faster gameplay, eat your enemys and shoot out viruses of your own, becoming the biggest. Midagi sellist, siis nagu nad saavad aru joinides, et mis selle mõte peaks olema.

**Comment by Netifriik** [comment]
Copy-paste see issue Pubgame_Client alla, seal teen UI uuendusi. Siia tee pigem mängusüsteemide kohta teemad. Muidu nõustun ideega.
